### PR TITLE
Passkey Capitalisation

### LINKED ISSUE #79: Only Capital Passkey Values allowed
**Describe the bug**
Only capital Passkey values are allowed. Users can't enter passkey in small cases even if the passkey's right.

**To Reproduce**

1. Go to 'HomeScreen'
2. Click on 'Join a Hike'
3. Enter a passkey in small case

**Expected behavior**
User should be able to enter the hike with the right passkey, irrespective of upper or small case entered.

**Demonstration**

https://user-images.githubusercontent.com/69353350/150589761-ba8fb45f-b4ff-408d-88d9-f03efedf3131.mov

**Environment**
- Device/emulator being used: Pixel 4XL
- OS (iOS/ Android); If Android then android version: <OS: 10>
- Flutter version: 2.8.1

**Are you working on this issue? (Yes/No)**
Yes, I am working on this issue

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
Fixes #79 

Describe the changes you have made in this PR - Changed random inputs into uppercase for easy interference

Screenshots of the changes (If any) - 

https://user-images.githubusercontent.com/69353350/150634971-ffb99542-cf69-4ac7-ae7f-ab100cf26d8c.mov

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

File: lib/components/create_join_dialog.dart [hunk 1]
```diff
@@ -258,10 +258,12 @@ class CreateJoinBeaconDialog {
                     child: Padding(
                       padding: const EdgeInsets.all(4.0),
                       child: TextFormField(
+                        keyboardType: TextInputType.text,
+                        textCapitalization: TextCapitalization.words,
```
Comment (nb9960) [inline lib/components/create_join_dialog.dart:262]:
```suggestion
                        textCapitalization: TextCapitalization.characters,
```

Comment (ItsAdityaKSingh) [reply lib/components/create_join_dialog.dart]: Done!
